spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interview_managerment
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tiendat187

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
#    init:
#      mode: always
#      data-locations: classpath:db/data.sql


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


